# Generated by Django 6.0 on 2026-01-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FechaBloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Selecciona el día que NO se podrá agendar.', unique=True)),
                ('motivo', models.CharField(choices=[('FERIADO', 'Feriado / Festivo'), ('LLENO', 'Agenda Completa'), ('MANTENCION', 'Mantención Interna'), ('OTRO', 'Otro Motivo')], default='LLENO', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Nota interna (opcional).', null=True)),
            ],
            options={
                'verbose_name': 'Día Bloqueado',
                'verbose_name_plural': 'Días Bloqueados (Agenda)',
                'ordering': ['fecha'],
            },
        ),
    ]
