# Generated by Django 6.0 on 2026-01-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrabajoEmpresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Proyecto')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción Corta')),
                ('categoria', models.CharField(choices=[('construccion', 'Construcción'), ('remodelacion', 'Remodelación'), ('industrial', 'Industrial')], default='construccion', max_length=20)),
                ('imagen', models.ImageField(upload_to='proyectos/', verbose_name='Foto del Proyecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Portafolio de Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
