# Generated by Django 6.0 on 2026-01-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrabajoEmpresa', '0002_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Grupo R&M SpA', max_length=100)),
                ('telefono_visible', models.CharField(help_text='Ej: +56 9 5400 0528', max_length=20, verbose_name='Teléfono (Visual)')),
                ('whatsapp_numero', models.CharField(help_text='Solo números, sin espacios ni símbolos. Ej: 56954000528', max_length=20, verbose_name='Número WhatsApp')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo de Contacto')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Link de Instagram')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección de Oficina')),
            ],
            options={
                'verbose_name': 'Configuración de Contacto',
                'verbose_name_plural': 'Configuración de Contacto',
            },
        ),
    ]
