# Generated by Django 6.0 on 2026-01-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrabajoEmpresa', '0003_datosempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosempresa',
            name='direccion',
        ),
    ]
