# Generated by Django 6.0 on 2026-01-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrabajoEmpresa', '0004_remove_datosempresa_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('construccion', 'Construcción'), ('remodelacion', 'Remodelación'), ('industrial', 'Industrial'), ('demarcacion_vial', 'Demarcación Vial')], default='construccion', max_length=20),
        ),
    ]
