# Generated by Django 6.0 on 2026-01-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrabajoEmpresa', '0005_alter_proyecto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempresa',
            name='video_descripcion',
            field=models.CharField(blank=True, help_text='Texto corto debajo del video', max_length=200, null=True, verbose_name='Descripción del Video'),
        ),
        migrations.AddField(
            model_name='datosempresa',
            name='video_youtube',
            field=models.URLField(blank=True, help_text='Ej: https://www.youtube.com/watch?v=dQw4w9WgXcQ', null=True, verbose_name='Enlace Video YouTube'),
        ),
    ]
