# Generated by Django 6.0 on 2026-01-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrabajoEmpresa', '0006_datosempresa_video_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='Imagen del Producto')),
                ('precio', models.IntegerField(blank=True, help_text="Opcional. Si se deja vacío, se puede mostrar 'Consultar'.", null=True, verbose_name='Precio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos en Venta',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
