# Generated by Django 6.0 on 2026-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrabajoEmpresa', '0007_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text="Dejar en blanco para 'Anónimo'", max_length=100, null=True)),
                ('comentario', models.TextField(max_length=100)),
                ('aprobado', models.BooleanField(default=False, help_text='Marcar para mostrar en el sitio web')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
