# Generated by Django 6.0 on 2026-01-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrabajoEmpresa', '0008_testimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempresa',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de TikTok'),
        ),
    ]
