# Generated by Django 6.0 on 2026-01-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrabajoEmpresa', '0009_datosempresa_tiktok_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Foto Extra 1 (Opcional)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Foto Extra 2 (Opcional)'),
        ),
    ]
